name: "Build"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install nix
      uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup cachix
      uses: cachix/cachix-action@v14
      with:
        name: heimdall
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#packages.x86_64-linux.crowdsec-gatekeeper
    - run: nix build .#cross.x86_64-linux.aarch64-unknown-linux-gnu.crowdsec-gatekeeper
